// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VivaioInCloud.Catalog.Infrastructure;

#nullable disable

namespace VivaioInCloud.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221027085203_SeedItemTypes")]
    partial class SeedItemTypes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VivaioInCloud.Catalog.Entities.Models.CatalogItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<string>("CategoryId")
                        .HasColumnType("text")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAtUtc")
                        .HasColumnOrder(1000);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("CreatedBy")
                        .HasColumnOrder(1001);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("IsDeleted")
                        .HasColumnOrder(1004);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAtUtc")
                        .HasColumnOrder(1002);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("UpdatedBy")
                        .HasColumnOrder(1003);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CatalogItems", "dbo");
                });

            modelBuilder.Entity("VivaioInCloud.Catalog.Entities.Models.ItemType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAtUtc")
                        .HasColumnOrder(1000);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("CreatedBy")
                        .HasColumnOrder(1001);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("IsDeleted")
                        .HasColumnOrder(1004);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAtUtc")
                        .HasColumnOrder(1002);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("UpdatedBy")
                        .HasColumnOrder(1003);

                    b.HasKey("Id");

                    b.ToTable("ItemTypes", "dbo");

                    b.HasData(
                        new
                        {
                            Id = "210BEC9A-B503-41CC-B95B-4DE49191175A",
                            CreatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "alberi-ornamentali",
                            UpdatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "235D0B4B-5046-4759-8E7D-D60873E1F7E8",
                            CreatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "accessori",
                            UpdatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "32781F4C-381A-449A-A16B-3C57690D599A",
                            CreatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "potatura",
                            UpdatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "46981D42-DE4A-4084-8AAE-6DDFF896434C",
                            CreatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "terriccio",
                            UpdatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "572C7BE0-BFDC-4AE9-A056-AD568DF6A4BC",
                            CreatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "diserbante",
                            UpdatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "64CA104F-EB10-4539-9319-C667D1CBDFC0",
                            CreatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "piante-da-interno",
                            UpdatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "67D10465-8B17-479A-9859-83D16B11DD84",
                            CreatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "piante-da-esterno",
                            UpdatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "7DA220D3-70EF-424D-9BFD-BFD4D290664D",
                            CreatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "alberi-da-frutto",
                            UpdatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "9CF6AB99-7A88-40B2-8D19-23868DCAFD03",
                            CreatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "vasi",
                            UpdatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "A50108A3-AA1A-4ED8-AED6-500B906830C9",
                            CreatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "prato",
                            UpdatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "A5475794-16F9-4C66-9E39-9E48D94941B9",
                            CreatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "barbecue",
                            UpdatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "BA4A9EDE-54EB-4768-875F-36DA8A6D94BC",
                            CreatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "cura-e-manutenzione",
                            UpdatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "CDCD18A8-9DF4-4224-984D-E8D0FFE2AD2B",
                            CreatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "serre",
                            UpdatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "CE826748-979B-4E75-B79A-37B11E19DEDF",
                            CreatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "gazebo",
                            UpdatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "D68FB54D-0369-488B-8D16-38970FF26896",
                            CreatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "rose",
                            UpdatedAtUtc = new DateTime(2022, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        });
                });

            modelBuilder.Entity("VivaioInCloud.Catalog.Entities.Models.CatalogItem", b =>
                {
                    b.HasOne("VivaioInCloud.Catalog.Entities.Models.ItemType", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("VivaioInCloud.Catalog.Entities.Models.ItemType", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
