// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VivaioInCloud.Catalog.Infrastructure;

#nullable disable

namespace VivaioInCloud.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221111145517_SeedingData")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VivaioInCloud.Catalog.Entities.Models.CatalogItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<string>("CategoryId")
                        .HasColumnType("text")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAtUtc")
                        .HasColumnOrder(1000);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("CreatedBy")
                        .HasColumnOrder(1001);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("IsDeleted")
                        .HasColumnOrder(1004);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAtUtc")
                        .HasColumnOrder(1002);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("UpdatedBy")
                        .HasColumnOrder(1003);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CatalogItems", "dbo");

                    b.HasData(
                        new
                        {
                            Id = "a36f7001-25ca-4a8e-9206-7f0580007fcc",
                            CategoryId = "210bec9a-b503-41cc-b95b-4de49191175a",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            IsDeleted = false,
                            Title = "Baobab",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "41c8c8d9-ee66-4bdb-9e41-f40cc24bf653",
                            CategoryId = "210bec9a-b503-41cc-b95b-4de49191175a",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            IsDeleted = false,
                            Title = "Cipresso",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "f300bad3-6a51-4874-a4c9-ae0de46bb1e3",
                            CategoryId = "210bec9a-b503-41cc-b95b-4de49191175a",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            IsDeleted = false,
                            Title = "Pino",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "c54b5a2b-a3de-485c-b4da-98ca35ac3c4e",
                            CategoryId = "235d0b4b-5046-4759-8e7d-d60873e1f7e8",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            IsDeleted = false,
                            Title = "Guanti",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "eee10013-3831-446e-9a0e-754f327c7af3",
                            CategoryId = "32781f4c-381a-449a-a16b-3c57690d599a",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            IsDeleted = false,
                            Title = "Cesoie",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "39be91a5-0f25-4fc7-869a-6225f89d8764",
                            CategoryId = "46981d42-de4a-4084-8aae-6ddff896434c",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            IsDeleted = false,
                            Title = "Letame Buono",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "188ad023-a2d4-4874-b84a-12a528e35073",
                            CategoryId = "572c7be0-bfdc-4ae9-a056-ad568df6a4bc",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            IsDeleted = false,
                            Title = "Kill 'Em All",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "281407cb-0008-43fc-ac68-4f924b6edaa8",
                            CategoryId = "64ca104f-eb10-4539-9319-c667d1cbdfc0",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            IsDeleted = false,
                            Title = "Orchidea",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "3c9eb92e-d41e-474e-98e2-c3b529a28850",
                            CategoryId = "64ca104f-eb10-4539-9319-c667d1cbdfc0",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            IsDeleted = false,
                            Title = "Mangia Fumo",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "b40b820d-f2f4-47c2-8213-c15f0c3346db",
                            CategoryId = "64ca104f-eb10-4539-9319-c667d1cbdfc0",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            IsDeleted = false,
                            Title = "Pianta Carnivora",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "ec4948f9-3892-4371-a460-a877007d80c1",
                            CategoryId = "64ca104f-eb10-4539-9319-c667d1cbdfc0",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            IsDeleted = false,
                            Title = "Grassa",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "4ebeb1b3-85e2-4715-b0b4-5f6a111be9f7",
                            CategoryId = "64ca104f-eb10-4539-9319-c667d1cbdfc0",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            IsDeleted = false,
                            Title = "Carnivora",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "fef09731-61ed-4617-a14b-34bab5b978dd",
                            CategoryId = "7da220d3-70ef-424d-9bfd-bfd4d290664d",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            IsDeleted = false,
                            Title = "Cigliegio",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "b4b3f08e-8c41-49b6-9767-b606b369fc77",
                            CategoryId = "7da220d3-70ef-424d-9bfd-bfd4d290664d",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            IsDeleted = false,
                            Title = "Pesco",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "51f52191-a956-4dfe-9dca-858270681a2d",
                            CategoryId = "7da220d3-70ef-424d-9bfd-bfd4d290664d",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            IsDeleted = false,
                            Title = "Pero",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "18cc9a4e-5b6c-4d9f-bd97-82b660d83f81",
                            CategoryId = "7da220d3-70ef-424d-9bfd-bfd4d290664d",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            IsDeleted = false,
                            Title = "Banano",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "314011b0-57c8-458d-8267-fe93549d01fb",
                            CategoryId = "7da220d3-70ef-424d-9bfd-bfd4d290664d",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            IsDeleted = false,
                            Title = "Avocado",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "31623bc9-5c07-48df-86d2-84f0b592d823",
                            CategoryId = "a50108a3-aa1a-4ed8-aed6-500b906830c9",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            IsDeleted = false,
                            Title = "Bello Verde",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "3c375fe9-3625-4ffd-8693-21bdc963451d",
                            CategoryId = "a5475794-16f9-4c66-9e39-9e48d94941b9",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            IsDeleted = false,
                            Title = "Master Griller",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "315ffca6-1e96-4bc9-bbdb-85c1abeff49f",
                            CategoryId = "a5475794-16f9-4c66-9e39-9e48d94941b9",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            IsDeleted = false,
                            Title = "Caverman",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "23b121b4-60f7-4bd1-acd3-d9d9ac639132",
                            CategoryId = "cdcd18a8-9df4-4224-984d-e8d0ffe2ad2b",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            IsDeleted = false,
                            Title = "Piccola",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "ac191fca-d358-46f9-ae17-28dfc9759566",
                            CategoryId = "cdcd18a8-9df4-4224-984d-e8d0ffe2ad2b",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            IsDeleted = false,
                            Title = "Media",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "e9581aba-cbde-4dbc-a0c4-51ff798dee11",
                            CategoryId = "cdcd18a8-9df4-4224-984d-e8d0ffe2ad2b",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            IsDeleted = false,
                            Title = "Grande",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        });
                });

            modelBuilder.Entity("VivaioInCloud.Catalog.Entities.Models.ItemType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAtUtc")
                        .HasColumnOrder(1000);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("CreatedBy")
                        .HasColumnOrder(1001);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("IsDeleted")
                        .HasColumnOrder(1004);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAtUtc")
                        .HasColumnOrder(1002);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("UpdatedBy")
                        .HasColumnOrder(1003);

                    b.HasKey("Id");

                    b.ToTable("ItemTypes", "dbo");

                    b.HasData(
                        new
                        {
                            Id = "210bec9a-b503-41cc-b95b-4de49191175a",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "alberi-ornamentali",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "235d0b4b-5046-4759-8e7d-d60873e1f7e8",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "accessori",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "32781f4c-381a-449a-a16b-3c57690d599a",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "potatura",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "46981d42-de4a-4084-8aae-6ddff896434c",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "terriccio",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "572c7be0-bfdc-4ae9-a056-ad568df6a4bc",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "diserbante",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "64ca104f-eb10-4539-9319-c667d1cbdfc0",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "piante-da-interno",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "67d10465-8b17-479a-9859-83d16b11dd84",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "piante-da-esterno",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "7da220d3-70ef-424d-9bfd-bfd4d290664d",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "alberi-da-frutto",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "9cf6ab99-7a88-40b2-8d19-23868dcafd03",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "vasi",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "a50108a3-aa1a-4ed8-aed6-500b906830c9",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "prato",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "a5475794-16f9-4c66-9e39-9e48d94941b9",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "barbecue",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "ba4a9ede-54eb-4768-875f-36da8a6d94bc",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "cura-e-manutenzione",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "cdcd18a8-9df4-4224-984d-e8d0ffe2ad2b",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "serre",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "ce826748-979b-4e75-b79a-37b11e19dedf",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "gazebo",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        },
                        new
                        {
                            Id = "d68fb54d-0369-488b-8d16-38970ff26896",
                            CreatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEEDER",
                            IsDeleted = false,
                            Name = "rose",
                            UpdatedAtUtc = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "SEEDER"
                        });
                });

            modelBuilder.Entity("VivaioInCloud.Catalog.Entities.Models.UserPreference", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<string>("ItemTypeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(2);

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("UserPreferences", "dbo");

                    b.HasData(
                        new
                        {
                            Id = "31db58f7-d710-4b43-a568-dffd582a6b2a",
                            ItemTypeId = "64ca104f-eb10-4539-9319-c667d1cbdfc0",
                            OwnerId = "13017f42-1786-4d94-9702-6e687f578a47"
                        },
                        new
                        {
                            Id = "35ca3132-2ea5-42b6-bbb2-35e57365b4ac",
                            ItemTypeId = "a5475794-16f9-4c66-9e39-9e48d94941b9",
                            OwnerId = "13017f42-1786-4d94-9702-6e687f578a47"
                        },
                        new
                        {
                            Id = "51b69010-08bf-44f3-aaa9-94bc4855bf70",
                            ItemTypeId = "64ca104f-eb10-4539-9319-c667d1cbdfc0",
                            OwnerId = "13017f42-1786-4d94-9702-6e687f578a47"
                        },
                        new
                        {
                            Id = "cf648d46-8e18-4f08-bf6a-f38c53006a42",
                            ItemTypeId = "210bec9a-b503-41cc-b95b-4de49191175a",
                            OwnerId = "7a63bbf1-4346-4aa7-a273-358f66224527"
                        },
                        new
                        {
                            Id = "7fa4edf6-6b08-45ff-ac29-266be4592457",
                            ItemTypeId = "235d0b4b-5046-4759-8e7d-d60873e1f7e8",
                            OwnerId = "7a63bbf1-4346-4aa7-a273-358f66224527"
                        },
                        new
                        {
                            Id = "16de1826-184b-4baa-9dd8-e05b886ee4a3",
                            ItemTypeId = "32781f4c-381a-449a-a16b-3c57690d599a",
                            OwnerId = "7a63bbf1-4346-4aa7-a273-358f66224527"
                        },
                        new
                        {
                            Id = "2150b65b-40da-43e9-8eaf-335ea59678bd",
                            ItemTypeId = "46981d42-de4a-4084-8aae-6ddff896434c",
                            OwnerId = "7a63bbf1-4346-4aa7-a273-358f66224527"
                        },
                        new
                        {
                            Id = "c4a047b2-227d-4337-8e49-d908d08e02c3",
                            ItemTypeId = "572c7be0-bfdc-4ae9-a056-ad568df6a4bc",
                            OwnerId = "7a63bbf1-4346-4aa7-a273-358f66224527"
                        },
                        new
                        {
                            Id = "c392b522-c068-45da-9b7c-ed0e97b7af7e",
                            ItemTypeId = "64ca104f-eb10-4539-9319-c667d1cbdfc0",
                            OwnerId = "7a63bbf1-4346-4aa7-a273-358f66224527"
                        },
                        new
                        {
                            Id = "d03c8746-715b-4006-b340-95eb981b7c09",
                            ItemTypeId = "67d10465-8b17-479a-9859-83d16b11dd84",
                            OwnerId = "7a63bbf1-4346-4aa7-a273-358f66224527"
                        },
                        new
                        {
                            Id = "5c1674e5-13ff-4377-a772-cf1a9251dac1",
                            ItemTypeId = "7da220d3-70ef-424d-9bfd-bfd4d290664d",
                            OwnerId = "7a63bbf1-4346-4aa7-a273-358f66224527"
                        },
                        new
                        {
                            Id = "b0705c45-b1b2-414b-a077-c5a9b6b325bb",
                            ItemTypeId = "9cf6ab99-7a88-40b2-8d19-23868dcafd03",
                            OwnerId = "7a63bbf1-4346-4aa7-a273-358f66224527"
                        },
                        new
                        {
                            Id = "28584503-2dd7-4534-9b38-162aa29078ad",
                            ItemTypeId = "a50108a3-aa1a-4ed8-aed6-500b906830c9",
                            OwnerId = "7a63bbf1-4346-4aa7-a273-358f66224527"
                        },
                        new
                        {
                            Id = "c5513422-5ec3-49f9-9797-74ce19b68989",
                            ItemTypeId = "a5475794-16f9-4c66-9e39-9e48d94941b9",
                            OwnerId = "7a63bbf1-4346-4aa7-a273-358f66224527"
                        },
                        new
                        {
                            Id = "db7ada8d-f91e-4116-8cba-785c1518f908",
                            ItemTypeId = "ba4a9ede-54eb-4768-875f-36da8a6d94bc",
                            OwnerId = "7a63bbf1-4346-4aa7-a273-358f66224527"
                        },
                        new
                        {
                            Id = "20c155e4-724e-4c23-97d8-25b280a90375",
                            ItemTypeId = "cdcd18a8-9df4-4224-984d-e8d0ffe2ad2b",
                            OwnerId = "7a63bbf1-4346-4aa7-a273-358f66224527"
                        },
                        new
                        {
                            Id = "9095b093-1163-4d71-83cc-82fa87fa9c7e",
                            ItemTypeId = "ce826748-979b-4e75-b79a-37b11e19dedf",
                            OwnerId = "7a63bbf1-4346-4aa7-a273-358f66224527"
                        },
                        new
                        {
                            Id = "4029e41f-6816-4243-8499-8a57656d6af0",
                            ItemTypeId = "d68fb54d-0369-488b-8d16-38970ff26896",
                            OwnerId = "7a63bbf1-4346-4aa7-a273-358f66224527"
                        });
                });

            modelBuilder.Entity("VivaioInCloud.Catalog.Entities.Models.CatalogItem", b =>
                {
                    b.HasOne("VivaioInCloud.Catalog.Entities.Models.ItemType", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("VivaioInCloud.Catalog.Entities.Models.UserPreference", b =>
                {
                    b.HasOne("VivaioInCloud.Catalog.Entities.Models.ItemType", "ItemType")
                        .WithMany("UserPreferences")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("VivaioInCloud.Catalog.Entities.Models.ItemType", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("UserPreferences");
                });
#pragma warning restore 612, 618
        }
    }
}
