version: '3'

services:

  database:
    image: 'postgres:latest'
    container_name: my_db
    hostname: my_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_DEFAULT}
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    networks:
      - postgres
    ports:
      - 5432:5432
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - ./pgadmin/:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

  identity:
    image: identity
    depends_on:
      database:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: ${CURRENT_ENV}
      ConnectionStrings__IdentityDatabase: ${IDENTITY_DATABASE}
      JWT__Audience: ${JWT_AUDIENCE}
      JWT__Issuer: ${JWT_ISSUER}
      JWT__AccessTokenExpirationHours: ${JWT_ACCESS_TOKEN_EXPIRATION_H}
      JWT__RefreshTokenExpirationDays: ${JWT_REFRESH_TOKEN_EXPIRATION_D}
      JWT__PrivateKey: ${JWT_PRIVATE_KEY}
      JWT__PublicKey: ${JWT_PUBLIC_KEY}
      AccountRedirectUrls__ConfirmAccountUrl: ${ACCOUNT_CONFIRM_ACCOUNT_URL}
      AccountRedirectUrls__ResetPasswordUrl: ${ACCOUNT_RESET_PASSWORD_URL}
    ports:
     - "5001:1050"

  catalog:
    image: catalog
    depends_on:
      database:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: ${CURRENT_ENV}
      ConnectionStrings__CatalogDatabase: ${CATALOG_DATABASE}
      JWT__Audience: ${JWT_AUDIENCE}
      JWT__Issuer: ${JWT_ISSUER}
      JWT__PublicKey: ${JWT_PUBLIC_KEY}
    ports:
     - "5002:1060"

  notification:
    image: notification
    depends_on:
      database:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: ${CURRENT_ENV}
      ConnectionStrings__NotificationDatabase: ${NOTIFICATION_DATABASE}
      JWT__Audience: ${JWT_AUDIENCE}
      JWT__Issuer: ${JWT_ISSUER}
      JWT__PublicKey: ${JWT_PUBLIC_KEY}
    ports:
     - "5003:1070"

networks:
  rabbitmq_go_net:
    driver: bridge
  postgres:
    driver: bridge


